version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        image: feedstock:1.0
        container_name: feedstock

        ports:
            - 80:80

        volumes:
            - ./public:/usr/share/nginx/html
            - ./nginx:/etc/nginx